// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('app', []);

  app.controller('MainController', function($scope) {
    var sum;
    $scope.target = 150;
    $scope.order = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
    $scope.days = {
      MON: 0,
      TUE: 0,
      WED: 0,
      THU: 0,
      FRI: 0,
      SAT: 0,
      SUN: 0
    };
    sum = function() {
      var count, day, total, _ref;
      total = 0;
      _ref = $scope.days;
      for (day in _ref) {
        count = _ref[day];
        total += parseInt(count);
      }
      return total;
    };
    $scope.metTarget = function() {
      return $scope.sum >= $scope.target;
    };
    return $scope.$watchCollection('days', function() {
      return $scope.sum = sum();
    });
  });

}).call(this);
